/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelView;

import control.AnabulControl;
import control.AnjingControl;
import control.KucingControl;
import java.awt.Component;

import exception.InputKosongException;
import exception.InputSpecialAtributeException;
import javax.swing.JOptionPane;
import model.Anabul;
import model.Anjing;
import model.Kucing;

public class AnabulMainPanel extends javax.swing.JPanel {
    private AnabulControl ac = new AnabulControl();
    private AnjingControl anc = new AnjingControl();
    private KucingControl kc = new KucingControl();
    private Anabul a = null;
    private Anjing an = null;
    private Kucing kcg = null;
    String actionAnabul = null;
    int idAnabul = 0;
    private Component rootPane;
    
    public AnabulMainPanel() {
        initComponents();
        setOpaque(false);
        showAnabul();
        setComponentsAnabul(false);
        setAnabulEditDeleteButton(false);
        clearText();        
    }
    
    public void inputKosongAnabulException() throws InputKosongException{
        if(namaAnabulInputTextField.getText().isEmpty() || umurAnabulInputTextfield.getText().isEmpty())
            throw new InputKosongException();
    }

    private void InputSpecialAtributeAnabulException() throws InputSpecialAtributeException{
        if(isInteger(specialAtributeInputTextfield.getText()))
            throw new InputSpecialAtributeException();
    }

    public boolean isInteger(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    public void setComponentsAnabul(boolean value){
        idAnabulInputTextField.setEnabled(value);
        namaAnabulInputTextField.setEnabled(value);
        umurAnabulInputTextfield.setEnabled(value);
        jenisAnabulInputButton.setEnabled(value);
    }
    
    public void setAnabulEditDeleteButton(boolean value){
        barukanAnabulButton.setEnabled(value);
        hapusAnabulButton.setEnabled(value);
    }
    
    public void clearText(){
        idAnabulInputTextField.setText("");
        namaAnabulInputTextField.setText("");
        umurAnabulInputTextfield.setText("");
        jenisAnabulInputButton.setText("");
        searchAnabulInputTextField.setText("");
        specialAtributeInputTextfield.setText("");
        specialAtributeInputLabel.setText("");
    }
    
    public void showAnabul(){
        kucingTextArea.setText("List Kucing: \n ============= \n"+kc.showStringAnabul());
        anjingTextArea.setText("List Anjing: \n ============= \n"+anc.showStringAnabul());
    }

    private boolean anjingIsSelected(){
        return jenisAnabulInputButton.getText().equals("Anjing");
    }
    
    private void doSearchAnabul(){
        if(searchAnabulInputTextField.getText().isEmpty())
            return;
        
            a = kc.searchDataAnabul(searchAnabulInputTextField.getText());
            
        if(a != null){
            setAnabulEditDeleteButton(true);
            idAnabulInputTextField.setText(a.getId_anabul());
            namaAnabulInputTextField.setText(a.getNama());
            umurAnabulInputTextfield.setText(Integer.toString(a.getUmur()));
            jenisAnabulInputButton.setText(a.getJenis());
            setSpecialAtributeLabel();
            specialAtributeInputTextfield.setText(a.getSpecial());
        }else{
            JOptionPane.showMessageDialog(rootPane, "NOT FOUND !!!");
        }
    }

    private void setSpecialAtributeLabel(){
        if(jenisAnabulInputButton.getText().equals("Anjing")){
            specialAtributeInputLabel.setText("Ras");
        }else{
            specialAtributeInputLabel.setText("Jenis Bulu");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        searchAnabulInputPanel = new javax.swing.JPanel();
        searchKendaraanInputLabel = new javax.swing.JLabel();
        searchAnabulInputTextField = new javax.swing.JTextField();
        searchAnabulInputButton = new javax.swing.JButton();
        kendaraanFormPanel = new javax.swing.JPanel();
        anabulButtonPanel = new javax.swing.JPanel();
        barukanAnabulButton = new javax.swing.JButton();
        hapusAnabulButton = new javax.swing.JButton();
        tambahAnabulButton = new javax.swing.JButton();
        idKendaraanInputPanel = new javax.swing.JPanel();
        idAnabulInputLabel = new javax.swing.JLabel();
        idAnabulInputTextField = new javax.swing.JTextField();
        namaAnabulInputPanel = new javax.swing.JPanel();
        namaAnabulInputLabel = new javax.swing.JLabel();
        namaAnabulInputTextField = new javax.swing.JTextField();
        umurAnabulInputPanel = new javax.swing.JPanel();
        umurAnabulInputLabel = new javax.swing.JLabel();
        umurAnabulInputTextfield = new javax.swing.JTextField();
        jenisAnabulInputPanel = new javax.swing.JPanel();
        jenisAnabulInputLabel = new javax.swing.JLabel();
        jenisAnabulInputButton = new javax.swing.JButton();
        specialAtributeInputPanel = new javax.swing.JPanel();
        specialAtributeInputLabel = new javax.swing.JLabel();
        specialAtributeInputTextfield = new javax.swing.JTextField();
        simpanKendaraanButton = new javax.swing.JButton();
        kucingScrollPane = new javax.swing.JScrollPane();
        kucingTextArea = new javax.swing.JTextArea();
        anjingScrollPane = new javax.swing.JScrollPane();
        anjingTextArea = new javax.swing.JTextArea();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchAnabulInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchKendaraanInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchKendaraanInputLabel.setText("Pencarian Anabul");

        searchAnabulInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchAnabulInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchAnabulInputTextFieldKeyPressed(evt);
            }
        });

        searchAnabulInputButton.setBackground(new java.awt.Color(27, 26, 85));
        searchAnabulInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchAnabulInputButton.setForeground(new java.awt.Color(255, 255, 255));
        searchAnabulInputButton.setText("Cari");
        searchAnabulInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAnabulInputButtonActionPerformed(evt);
            }
        });

        kendaraanFormPanel.setBackground(new java.awt.Color(255, 255, 255));

        anabulButtonPanel.setBackground(new java.awt.Color(255, 255, 255));

        barukanAnabulButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanAnabulButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanAnabulButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanAnabulButton.setText("Barukan");
        barukanAnabulButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanAnabulButtonActionPerformed(evt);
            }
        });

        hapusAnabulButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusAnabulButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusAnabulButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusAnabulButton.setText("Hapus");
        hapusAnabulButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusAnabulButtonActionPerformed(evt);
            }
        });

        tambahAnabulButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahAnabulButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahAnabulButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahAnabulButton.setText("Tambah");
        tambahAnabulButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahAnabulButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout anabulButtonPanelLayout = new javax.swing.GroupLayout(anabulButtonPanel);
        anabulButtonPanel.setLayout(anabulButtonPanelLayout);
        anabulButtonPanelLayout.setHorizontalGroup(
            anabulButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anabulButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahAnabulButton)
                .addGap(18, 18, 18)
                .addComponent(barukanAnabulButton)
                .addGap(18, 18, 18)
                .addComponent(hapusAnabulButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        anabulButtonPanelLayout.setVerticalGroup(
            anabulButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anabulButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(anabulButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanAnabulButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahAnabulButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusAnabulButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        idKendaraanInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        idAnabulInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idAnabulInputLabel.setText("ID Kendaraan");

        idAnabulInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idAnabulInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAnabulInputTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idKendaraanInputPanelLayout = new javax.swing.GroupLayout(idKendaraanInputPanel);
        idKendaraanInputPanel.setLayout(idKendaraanInputPanelLayout);
        idKendaraanInputPanelLayout.setHorizontalGroup(
            idKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idKendaraanInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idAnabulInputTextField)
                    .addComponent(idAnabulInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        idKendaraanInputPanelLayout.setVerticalGroup(
            idKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idKendaraanInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idAnabulInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idAnabulInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaAnabulInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        namaAnabulInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaAnabulInputLabel.setText("Nama");

        namaAnabulInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        javax.swing.GroupLayout namaAnabulInputPanelLayout = new javax.swing.GroupLayout(namaAnabulInputPanel);
        namaAnabulInputPanel.setLayout(namaAnabulInputPanelLayout);
        namaAnabulInputPanelLayout.setHorizontalGroup(
            namaAnabulInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaAnabulInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaAnabulInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namaAnabulInputTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(namaAnabulInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        namaAnabulInputPanelLayout.setVerticalGroup(
            namaAnabulInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaAnabulInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaAnabulInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaAnabulInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        umurAnabulInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        umurAnabulInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        umurAnabulInputLabel.setText("Umur");

        umurAnabulInputTextfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        umurAnabulInputTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                umurAnabulInputTextfieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout umurAnabulInputPanelLayout = new javax.swing.GroupLayout(umurAnabulInputPanel);
        umurAnabulInputPanel.setLayout(umurAnabulInputPanelLayout);
        umurAnabulInputPanelLayout.setHorizontalGroup(
            umurAnabulInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(umurAnabulInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(umurAnabulInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(umurAnabulInputTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(umurAnabulInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        umurAnabulInputPanelLayout.setVerticalGroup(
            umurAnabulInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(umurAnabulInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(umurAnabulInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(umurAnabulInputTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jenisAnabulInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        jenisAnabulInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jenisAnabulInputLabel.setText("Jenis Anabul");

        jenisAnabulInputButton.setBackground(new java.awt.Color(153, 204, 255));
        jenisAnabulInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jenisAnabulInputButton.setText("Anjing");
        jenisAnabulInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisAnabulInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jenisAnabulInputPanelLayout = new javax.swing.GroupLayout(jenisAnabulInputPanel);
        jenisAnabulInputPanel.setLayout(jenisAnabulInputPanelLayout);
        jenisAnabulInputPanelLayout.setHorizontalGroup(
            jenisAnabulInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jenisAnabulInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jenisAnabulInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jenisAnabulInputPanelLayout.createSequentialGroup()
                        .addComponent(jenisAnabulInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jenisAnabulInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jenisAnabulInputPanelLayout.setVerticalGroup(
            jenisAnabulInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jenisAnabulInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jenisAnabulInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenisAnabulInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout kendaraanFormPanelLayout = new javax.swing.GroupLayout(kendaraanFormPanel);
        kendaraanFormPanel.setLayout(kendaraanFormPanelLayout);
        kendaraanFormPanelLayout.setHorizontalGroup(
            kendaraanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kendaraanFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kendaraanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kendaraanFormPanelLayout.createSequentialGroup()
                        .addComponent(anabulButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 308, Short.MAX_VALUE))
                    .addGroup(kendaraanFormPanelLayout.createSequentialGroup()
                        .addGroup(kendaraanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(namaAnabulInputPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idKendaraanInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(kendaraanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jenisAnabulInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(umurAnabulInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        kendaraanFormPanelLayout.setVerticalGroup(
            kendaraanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kendaraanFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anabulButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kendaraanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idKendaraanInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(umurAnabulInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kendaraanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaAnabulInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jenisAnabulInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        specialAtributeInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        specialAtributeInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        specialAtributeInputLabel.setText("Ras");

        specialAtributeInputTextfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        specialAtributeInputTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                specialAtributeInputTextfieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout specialAtributeInputPanelLayout = new javax.swing.GroupLayout(specialAtributeInputPanel);
        specialAtributeInputPanel.setLayout(specialAtributeInputPanelLayout);
        specialAtributeInputPanelLayout.setHorizontalGroup(
            specialAtributeInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialAtributeInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(specialAtributeInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(specialAtributeInputTextfield)
                    .addComponent(specialAtributeInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                .addContainerGap(329, Short.MAX_VALUE))
        );
        specialAtributeInputPanelLayout.setVerticalGroup(
            specialAtributeInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialAtributeInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(specialAtributeInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specialAtributeInputTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout searchAnabulInputPanelLayout = new javax.swing.GroupLayout(searchAnabulInputPanel);
        searchAnabulInputPanel.setLayout(searchAnabulInputPanelLayout);
        searchAnabulInputPanelLayout.setHorizontalGroup(
            searchAnabulInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchAnabulInputPanelLayout.createSequentialGroup()
                .addGroup(searchAnabulInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchAnabulInputPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(searchAnabulInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchKendaraanInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(searchAnabulInputPanelLayout.createSequentialGroup()
                                .addComponent(searchAnabulInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchAnabulInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 531, Short.MAX_VALUE))))
                    .addGroup(searchAnabulInputPanelLayout.createSequentialGroup()
                        .addComponent(kendaraanFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(specialAtributeInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        searchAnabulInputPanelLayout.setVerticalGroup(
            searchAnabulInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchAnabulInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchKendaraanInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchAnabulInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchAnabulInputTextField)
                    .addComponent(searchAnabulInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGroup(searchAnabulInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchAnabulInputPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kendaraanFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchAnabulInputPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(specialAtributeInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        simpanKendaraanButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanKendaraanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        simpanKendaraanButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanKendaraanButton.setText("Simpan");
        simpanKendaraanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanKendaraanButtonActionPerformed(evt);
            }
        });

        kucingScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        kucingScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        kucingTextArea.setColumns(20);
        kucingTextArea.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        kucingTextArea.setRows(5);
        kucingScrollPane.setViewportView(kucingTextArea);

        anjingScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        anjingTextArea.setColumns(20);
        anjingTextArea.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        anjingTextArea.setRows(5);
        anjingTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        anjingScrollPane.setViewportView(anjingTextArea);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchAnabulInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(anjingScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kucingScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(simpanKendaraanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchAnabulInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simpanKendaraanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anjingScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kucingScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchAnabulInputTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchAnabulInputTextFieldKeyPressed
        
    }//GEN-LAST:event_searchAnabulInputTextFieldKeyPressed

    private void searchAnabulInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAnabulInputButtonActionPerformed
        doSearchAnabul();
    }//GEN-LAST:event_searchAnabulInputButtonActionPerformed

    private void barukanAnabulButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanAnabulButtonActionPerformed
        actionAnabul = "update";
        setComponentsAnabul(true);
        idAnabulInputTextField.setEnabled(false);
    }//GEN-LAST:event_barukanAnabulButtonActionPerformed

    private void hapusAnabulButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusAnabulButtonActionPerformed
        int opsi = JOptionPane.showConfirmDialog(rootPane, "Yakin Ingin Hapus ?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if( opsi == JOptionPane.NO_OPTION || opsi == JOptionPane.CLOSED_OPTION)
            return;
        
        kc.deteleDataAnabul(idAnabulInputTextField.getText());
        clearText();
        setAnabulEditDeleteButton(false);
        setComponentsAnabul(false);
        showAnabul();
    }//GEN-LAST:event_hapusAnabulButtonActionPerformed

    private void tambahAnabulButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahAnabulButtonActionPerformed
        actionAnabul = "add";
        clearText();
        setAnabulEditDeleteButton(false);
        setComponentsAnabul(true);
        setAnabulEditDeleteButton(false);
        
        idAnabulInputTextField.setEnabled(false);
        idAnabulInputTextField.setText(kc.generateId());
        jenisAnabulInputButton.setText("Anjing");
        setSpecialAtributeLabel();
    }//GEN-LAST:event_tambahAnabulButtonActionPerformed

    private void idAnabulInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAnabulInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idAnabulInputTextFieldActionPerformed

    private void umurAnabulInputTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_umurAnabulInputTextfieldKeyTyped

    }//GEN-LAST:event_umurAnabulInputTextfieldKeyTyped

    private void jenisAnabulInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisAnabulInputButtonActionPerformed
        switch(jenisAnabulInputButton.getText()){
            case "Anjing": jenisAnabulInputButton.setText("Kucing"); break;
            case "Kucing": jenisAnabulInputButton.setText("Anjing"); break;
        }
        setSpecialAtributeLabel();
    }//GEN-LAST:event_jenisAnabulInputButtonActionPerformed

    private void simpanKendaraanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanKendaraanButtonActionPerformed
        if(actionAnabul == null)
            return;
        try{
            inputKosongAnabulException();
            InputSpecialAtributeAnabulException();
            
            if(JOptionPane.showConfirmDialog(rootPane, "yakin ingin melakukan " + actionAnabul + "?") == JOptionPane.CLOSED_OPTION)
                return;

            switch (actionAnabul){
                case "add":
                    if(anjingIsSelected()){
                        an = new Anjing(specialAtributeInputTextfield.getText(), namaAnabulInputTextField.getText(), 
                                jenisAnabulInputButton.getText(), Integer.parseInt(umurAnabulInputTextfield.getText()));
                        anc.insertDataAnabul(an);
                    }else{
                        kcg = new Kucing(specialAtributeInputTextfield.getText(), namaAnabulInputTextField.getText(), 
                                jenisAnabulInputButton.getText(), Integer.parseInt(umurAnabulInputTextfield.getText()));
                        kc.insertDataAnabul(kcg);
                    }
                    clearText();
                    setAnabulEditDeleteButton(false);
                    setComponentsAnabul(false);
                    showAnabul();
                    break;
                case "update":
                    if(anjingIsSelected()){
                        an = new Anjing(specialAtributeInputTextfield.getText(),idAnabulInputTextField.getText(), namaAnabulInputTextField.getText(), 
                                jenisAnabulInputButton.getText(), Integer.parseInt(umurAnabulInputTextfield.getText()));
                        anc.updateDataAnabul(an);
                    }else{
                        kcg = new Kucing(specialAtributeInputTextfield.getText(),idAnabulInputTextField.getText(), namaAnabulInputTextField.getText(), 
                                jenisAnabulInputButton.getText(), Integer.parseInt(umurAnabulInputTextfield.getText()));
                        kc.updateDataAnabul(kcg);
                    }
                    clearText();
                    setAnabulEditDeleteButton(false);
                    setComponentsAnabul(false);
                    showAnabul();
                    break;
                default:
                    break;
            }
            actionAnabul = null;
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(rootPane, e.message());
        }catch(InputSpecialAtributeException e){
            JOptionPane.showMessageDialog(rootPane, e.message(jenisAnabulInputButton.getText()));
        }
    }//GEN-LAST:event_simpanKendaraanButtonActionPerformed

    private void specialAtributeInputTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_specialAtributeInputTextfieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_specialAtributeInputTextfieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel anabulButtonPanel;
    private javax.swing.JScrollPane anjingScrollPane;
    private javax.swing.JTextArea anjingTextArea;
    private javax.swing.JButton barukanAnabulButton;
    private javax.swing.JButton hapusAnabulButton;
    private javax.swing.JLabel idAnabulInputLabel;
    private javax.swing.JTextField idAnabulInputTextField;
    private javax.swing.JPanel idKendaraanInputPanel;
    private javax.swing.JButton jenisAnabulInputButton;
    private javax.swing.JLabel jenisAnabulInputLabel;
    private javax.swing.JPanel jenisAnabulInputPanel;
    private javax.swing.JPanel kendaraanFormPanel;
    private javax.swing.JScrollPane kucingScrollPane;
    private javax.swing.JTextArea kucingTextArea;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaAnabulInputLabel;
    private javax.swing.JPanel namaAnabulInputPanel;
    private javax.swing.JTextField namaAnabulInputTextField;
    private javax.swing.JButton searchAnabulInputButton;
    private javax.swing.JPanel searchAnabulInputPanel;
    private javax.swing.JTextField searchAnabulInputTextField;
    private javax.swing.JLabel searchKendaraanInputLabel;
    private javax.swing.JButton simpanKendaraanButton;
    private javax.swing.JLabel specialAtributeInputLabel;
    private javax.swing.JPanel specialAtributeInputPanel;
    private javax.swing.JTextField specialAtributeInputTextfield;
    private javax.swing.JButton tambahAnabulButton;
    private javax.swing.JLabel umurAnabulInputLabel;
    private javax.swing.JPanel umurAnabulInputPanel;
    private javax.swing.JTextField umurAnabulInputTextfield;
    // End of variables declaration//GEN-END:variables
}
