/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelView;

import control.PemilikControl;
import exception.InputKosongException;
import exception.NoTelponException;
import java.awt.Component;
import javax.swing.JOptionPane;
import model.Pemilik;

public class PemilikMainPanel extends javax.swing.JPanel {
    private PemilikControl pc = new PemilikControl();
    private Pemilik p = null;
    String actionPemilik = null;
    int idPemilik = 0;
    private Component rootPane;
    
    
    private void inputKosongCustomerException() throws InputKosongException{
        if(namaPemilikInputTextField.getText().isEmpty() || umurInputTextField.getText().isEmpty() || nomorTeleponInputTextField.getText().isEmpty())
            throw new InputKosongException();
    }
    
    public boolean isInteger(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
            
    private void noTelponException() throws NoTelponException{
        if(!nomorTeleponInputTextField.getText().matches("^\\+?[0-9]+$"))
            throw new NoTelponException();
    }
    
    public PemilikMainPanel() {
        initComponents();
        setOpaque(false);
        showPemilik();
        setComponentsPemilik(false);        
        setEditDeleteButtonPemilik(false);        
        clearTextPemilik();
    }
    
    // Customer Set Komponen
    public void setComponentsPemilik(boolean value){
        namaPemilikInputTextField.setEnabled(value);
        nomorTeleponInputTextField.setEnabled(value);
        umurInputTextField.setEnabled(value);
    }
    
    // Customer Set Edit Delete Button
    public void setEditDeleteButtonPemilik(boolean value){
        barukanPemilikButton.setEnabled(value);
        hapusPemilikButton.setEnabled(value);
    }
    
    // Customer Clear Text
    public void clearTextPemilik(){
        namaPemilikInputTextField.setText("");
        nomorTeleponInputTextField.setText("");
        umurInputTextField.setText("");
        searchPemilikInputTextField.setText("");
    }
    
    public void showPemilik(){
        pemilikTextArea.setText("List Pemilik: \n ============= \n"+pc.showAllStringPemilik());
    }

    private void doSearchPemilik(){
        if(searchPemilikInputTextField.getText().isEmpty())
            return;
            Pemilik p = pc.searchPemilikById(Integer.parseInt(searchPemilikInputTextField.getText()));
            if(p == null ){
                JOptionPane.showMessageDialog(rootPane, "NOT FOUND !!!");
                return;
            }
            setEditDeleteButtonPemilik(true);
            clearTextPemilik();
            
            namaPemilikInputTextField.setText(p.getNama());
            nomorTeleponInputTextField.setText(p.getNotelp());
            umurInputTextField.setText(String.valueOf(p.getUmur()));
            
            idPemilik = p.getId_pemilik();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        searchCustomerInputPanel = new javax.swing.JPanel();
        searchPemilikInputLabel = new javax.swing.JLabel();
        searchPemilikInputTextField = new javax.swing.JTextField();
        searchPemilikInputButton = new javax.swing.JButton();
        pemilikFormPanel = new javax.swing.JPanel();
        CustomerButtonPanel = new javax.swing.JPanel();
        barukanPemilikButton = new javax.swing.JButton();
        hapusPemilikButton = new javax.swing.JButton();
        tambahPemilikButton = new javax.swing.JButton();
        namaPemilikPanel = new javax.swing.JPanel();
        namaPemilikInputLabel = new javax.swing.JLabel();
        namaPemilikInputTextField = new javax.swing.JTextField();
        nomorTeleponInputPanel = new javax.swing.JPanel();
        nomorTeleponInputLabel = new javax.swing.JLabel();
        nomorTeleponInputTextField = new javax.swing.JTextField();
        umurInputPanel = new javax.swing.JPanel();
        umurInputLabel = new javax.swing.JLabel();
        umurInputTextField = new javax.swing.JTextField();
        simpanCustomerButton = new javax.swing.JButton();
        pemilikScrollPane = new javax.swing.JScrollPane();
        pemilikTextArea = new javax.swing.JTextArea();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchCustomerInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchPemilikInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchPemilikInputLabel.setText("Pencarian Pemilik");

        searchPemilikInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchPemilikInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchPemilikInputTextFieldKeyTyped(evt);
            }
        });

        searchPemilikInputButton.setBackground(new java.awt.Color(27, 26, 85));
        searchPemilikInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchPemilikInputButton.setForeground(new java.awt.Color(255, 255, 255));
        searchPemilikInputButton.setText("Cari");
        searchPemilikInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPemilikInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchCustomerInputPanelLayout = new javax.swing.GroupLayout(searchCustomerInputPanel);
        searchCustomerInputPanel.setLayout(searchCustomerInputPanelLayout);
        searchCustomerInputPanelLayout.setHorizontalGroup(
            searchCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPemilikInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchCustomerInputPanelLayout.createSequentialGroup()
                        .addComponent(searchPemilikInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchPemilikInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchCustomerInputPanelLayout.setVerticalGroup(
            searchCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchPemilikInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchPemilikInputTextField)
                    .addComponent(searchPemilikInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pemilikFormPanel.setBackground(new java.awt.Color(255, 255, 255));
        pemilikFormPanel.setForeground(new java.awt.Color(255, 255, 255));

        CustomerButtonPanel.setBackground(new java.awt.Color(255, 255, 255));

        barukanPemilikButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanPemilikButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanPemilikButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanPemilikButton.setText("Barukan");
        barukanPemilikButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanPemilikButtonActionPerformed(evt);
            }
        });

        hapusPemilikButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusPemilikButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusPemilikButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusPemilikButton.setText("Hapus");
        hapusPemilikButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPemilikButtonActionPerformed(evt);
            }
        });

        tambahPemilikButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahPemilikButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahPemilikButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahPemilikButton.setText("Tambah");
        tambahPemilikButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPemilikButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CustomerButtonPanelLayout = new javax.swing.GroupLayout(CustomerButtonPanel);
        CustomerButtonPanel.setLayout(CustomerButtonPanelLayout);
        CustomerButtonPanelLayout.setHorizontalGroup(
            CustomerButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahPemilikButton)
                .addGap(18, 18, 18)
                .addComponent(barukanPemilikButton)
                .addGap(18, 18, 18)
                .addComponent(hapusPemilikButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        CustomerButtonPanelLayout.setVerticalGroup(
            CustomerButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomerButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanPemilikButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahPemilikButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusPemilikButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaPemilikPanel.setBackground(new java.awt.Color(255, 255, 255));
        namaPemilikPanel.setForeground(new java.awt.Color(255, 255, 255));

        namaPemilikInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaPemilikInputLabel.setText("Nama Pemilik");

        namaPemilikInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaPemilikInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPemilikInputTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout namaPemilikPanelLayout = new javax.swing.GroupLayout(namaPemilikPanel);
        namaPemilikPanel.setLayout(namaPemilikPanelLayout);
        namaPemilikPanelLayout.setHorizontalGroup(
            namaPemilikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaPemilikPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaPemilikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaPemilikInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaPemilikInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        namaPemilikPanelLayout.setVerticalGroup(
            namaPemilikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaPemilikPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaPemilikInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaPemilikInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nomorTeleponInputPanel.setBackground(new java.awt.Color(255, 255, 255));
        nomorTeleponInputPanel.setForeground(new java.awt.Color(255, 255, 255));

        nomorTeleponInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        nomorTeleponInputLabel.setText("Nomor Telepon");

        nomorTeleponInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        javax.swing.GroupLayout nomorTeleponInputPanelLayout = new javax.swing.GroupLayout(nomorTeleponInputPanel);
        nomorTeleponInputPanel.setLayout(nomorTeleponInputPanelLayout);
        nomorTeleponInputPanelLayout.setHorizontalGroup(
            nomorTeleponInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomorTeleponInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nomorTeleponInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomorTeleponInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomorTeleponInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nomorTeleponInputPanelLayout.setVerticalGroup(
            nomorTeleponInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomorTeleponInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomorTeleponInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomorTeleponInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        umurInputPanel.setBackground(new java.awt.Color(255, 255, 255));
        umurInputPanel.setForeground(new java.awt.Color(255, 255, 255));

        umurInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        umurInputLabel.setText("Umur");

        umurInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        javax.swing.GroupLayout umurInputPanelLayout = new javax.swing.GroupLayout(umurInputPanel);
        umurInputPanel.setLayout(umurInputPanelLayout);
        umurInputPanelLayout.setHorizontalGroup(
            umurInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(umurInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(umurInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(umurInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(umurInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        umurInputPanelLayout.setVerticalGroup(
            umurInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(umurInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(umurInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(umurInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pemilikFormPanelLayout = new javax.swing.GroupLayout(pemilikFormPanel);
        pemilikFormPanel.setLayout(pemilikFormPanelLayout);
        pemilikFormPanelLayout.setHorizontalGroup(
            pemilikFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemilikFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pemilikFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pemilikFormPanelLayout.createSequentialGroup()
                        .addGroup(pemilikFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nomorTeleponInputPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namaPemilikPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(umurInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pemilikFormPanelLayout.createSequentialGroup()
                        .addComponent(CustomerButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pemilikFormPanelLayout.setVerticalGroup(
            pemilikFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemilikFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CustomerButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pemilikFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pemilikFormPanelLayout.createSequentialGroup()
                        .addComponent(namaPemilikPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomorTeleponInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(umurInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        simpanCustomerButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanCustomerButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        simpanCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanCustomerButton.setText("Simpan");
        simpanCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanCustomerButtonActionPerformed(evt);
            }
        });

        pemilikScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pemilikTextArea.setColumns(20);
        pemilikTextArea.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        pemilikTextArea.setRows(5);
        pemilikScrollPane.setViewportView(pemilikTextArea);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchCustomerInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(pemilikFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 405, Short.MAX_VALUE)
                        .addComponent(simpanCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pemilikScrollPane))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchCustomerInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(simpanCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pemilikFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(pemilikScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchPemilikInputTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchPemilikInputTextFieldKeyTyped
        if(evt.getKeyChar()=='\n'){
            doSearchPemilik();
        }
    }//GEN-LAST:event_searchPemilikInputTextFieldKeyTyped

    private void searchPemilikInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPemilikInputButtonActionPerformed
        doSearchPemilik();
    }//GEN-LAST:event_searchPemilikInputButtonActionPerformed

    private void barukanPemilikButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanPemilikButtonActionPerformed
        actionPemilik = "update";
        setComponentsPemilik(true);
    }//GEN-LAST:event_barukanPemilikButtonActionPerformed

    private void hapusPemilikButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPemilikButtonActionPerformed
        clearTextPemilik();
        setEditDeleteButtonPemilik(false);
        setComponentsPemilik(false);
        
        int opsi = JOptionPane.showConfirmDialog(rootPane, "Yakin Ingin Hapus ?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if( opsi == JOptionPane.NO_OPTION || opsi == JOptionPane.CLOSED_OPTION){
            idPemilik = -1;
            return;
        }
        
        pc.deleteDataPemilik(idPemilik);
        idPemilik = -1;
        showPemilik();
    }//GEN-LAST:event_hapusPemilikButtonActionPerformed

    private void tambahPemilikButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPemilikButtonActionPerformed
        actionPemilik = "add";
        clearTextPemilik();
        setEditDeleteButtonPemilik(true);
        setComponentsPemilik(true);
    }//GEN-LAST:event_tambahPemilikButtonActionPerformed

    private void namaPemilikInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPemilikInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPemilikInputTextFieldActionPerformed

    private void simpanCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanCustomerButtonActionPerformed
        // TODO add your handling code here:
        if(actionPemilik == null)
            return;
        try{
            inputKosongCustomerException();
            noTelponException();
            if(JOptionPane.showConfirmDialog(rootPane, "yakin ingin melakukan " + actionPemilik + "?") == JOptionPane.CLOSED_OPTION)
                return;
            switch(actionPemilik){
            case "add":
                p = new Pemilik(namaPemilikInputTextField.getText(), Integer.parseInt(umurInputTextField.getText()), nomorTeleponInputTextField.getText());
                pc.insertDataPemilik(p);
                clearTextPemilik();
                setEditDeleteButtonPemilik(false);
                setComponentsPemilik(false);
                break;
            case "update":
                p = new Pemilik(namaPemilikInputTextField.getText(), Integer.parseInt(umurInputTextField.getText()), nomorTeleponInputTextField.getText());
                pc.updateDataPemilik(p, idPemilik);
                clearTextPemilik();
                setEditDeleteButtonPemilik(false);
                setComponentsPemilik(false);
                break;
            default:
                break;
        }
        showPemilik();
        actionPemilik = null;
        }catch(InputKosongException e){
            System.out.println(e);
        }catch(NoTelponException e){
            JOptionPane.showMessageDialog(rootPane, e.message());
        };
    }//GEN-LAST:event_simpanCustomerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CustomerButtonPanel;
    private javax.swing.JButton barukanPemilikButton;
    private javax.swing.JButton hapusPemilikButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaPemilikInputLabel;
    private javax.swing.JTextField namaPemilikInputTextField;
    private javax.swing.JPanel namaPemilikPanel;
    private javax.swing.JLabel nomorTeleponInputLabel;
    private javax.swing.JPanel nomorTeleponInputPanel;
    private javax.swing.JTextField nomorTeleponInputTextField;
    private javax.swing.JPanel pemilikFormPanel;
    private javax.swing.JScrollPane pemilikScrollPane;
    private javax.swing.JTextArea pemilikTextArea;
    private javax.swing.JPanel searchCustomerInputPanel;
    private javax.swing.JButton searchPemilikInputButton;
    private javax.swing.JLabel searchPemilikInputLabel;
    private javax.swing.JTextField searchPemilikInputTextField;
    private javax.swing.JButton simpanCustomerButton;
    private javax.swing.JButton tambahPemilikButton;
    private javax.swing.JLabel umurInputLabel;
    private javax.swing.JPanel umurInputPanel;
    private javax.swing.JTextField umurInputTextField;
    // End of variables declaration//GEN-END:variables
}
