package view;

import panelView.*;
import java.awt.Color;
import javax.swing.JComponent;

public class MainViewForm extends javax.swing.JFrame {
    private int selectedIndex = -1;
    
    private void setForm(JComponent com) {
        contentPanel.removeAll();
        contentPanel.add(com);
        contentPanel.repaint();
        contentPanel.revalidate();
    }
    
    private void recolorDefaultSwitchPanel() {
        repaint();
        pemilikPanel.setBackground(new Color(0, 0, 0, 0));
        anabulPanel.setBackground(new Color(0, 0, 0, 0));
    }

    public MainViewForm() {
        initComponents();
        recolorDefaultSwitchPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        logoIcon = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        pemilikPanel = new javax.swing.JPanel();
        pemilikLabel = new javax.swing.JLabel();
        anabulPanel = new javax.swing.JPanel();
        anabulLabel = new javax.swing.JLabel();
        daftarPerawatanPanel = new javax.swing.JPanel();
        daftarPerawatanLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setPreferredSize(new java.awt.Dimension(1360, 757));

        sidePanel.setBackground(new java.awt.Color(27, 26, 85));
        sidePanel.setPreferredSize(new java.awt.Dimension(160, 757));

        logoPanel.setBackground(new java.awt.Color(27, 26, 85));
        logoPanel.setPreferredSize(new java.awt.Dimension(140, 120));

        logoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-pet-50.png"))); // NOI18N

        logoLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 22)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel.setText("Pet Cura");

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoPanelLayout.createSequentialGroup()
                        .addComponent(logoLabel)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoPanelLayout.createSequentialGroup()
                        .addComponent(logoIcon)
                        .addGap(44, 44, 44))))
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(logoIcon)
                .addGap(18, 18, 18)
                .addComponent(logoLabel)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pemilikPanel.setBackground(new java.awt.Color(27, 26, 85));
        pemilikPanel.setPreferredSize(new java.awt.Dimension(140, 70));
        pemilikPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pemilikPanelMouseClicked(evt);
            }
        });

        pemilikLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        pemilikLabel.setForeground(new java.awt.Color(255, 255, 255));
        pemilikLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/customerIcon.png"))); // NOI18N
        pemilikLabel.setText("Pemilik");

        javax.swing.GroupLayout pemilikPanelLayout = new javax.swing.GroupLayout(pemilikPanel);
        pemilikPanel.setLayout(pemilikPanelLayout);
        pemilikPanelLayout.setHorizontalGroup(
            pemilikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemilikPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pemilikLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(62, 62, 62))
        );
        pemilikPanelLayout.setVerticalGroup(
            pemilikPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemilikPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pemilikLabel)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        anabulPanel.setBackground(new java.awt.Color(27, 26, 85));
        anabulPanel.setPreferredSize(new java.awt.Dimension(140, 70));
        anabulPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anabulPanelMouseClicked(evt);
            }
        });

        anabulLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        anabulLabel.setForeground(new java.awt.Color(255, 255, 255));
        anabulLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/paws (1).png"))); // NOI18N
        anabulLabel.setText("Anabul");

        javax.swing.GroupLayout anabulPanelLayout = new javax.swing.GroupLayout(anabulPanel);
        anabulPanel.setLayout(anabulPanelLayout);
        anabulPanelLayout.setHorizontalGroup(
            anabulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anabulPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anabulLabel)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        anabulPanelLayout.setVerticalGroup(
            anabulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anabulPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(anabulLabel)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        daftarPerawatanPanel.setBackground(new java.awt.Color(27, 26, 85));
        daftarPerawatanPanel.setPreferredSize(new java.awt.Dimension(140, 70));

        daftarPerawatanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        daftarPerawatanLabel.setForeground(new java.awt.Color(255, 255, 255));
        daftarPerawatanLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-book-26.png"))); // NOI18N
        daftarPerawatanLabel.setText("Daftar Perawatan");

        javax.swing.GroupLayout daftarPerawatanPanelLayout = new javax.swing.GroupLayout(daftarPerawatanPanel);
        daftarPerawatanPanel.setLayout(daftarPerawatanPanelLayout);
        daftarPerawatanPanelLayout.setHorizontalGroup(
            daftarPerawatanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daftarPerawatanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(daftarPerawatanLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        daftarPerawatanPanelLayout.setVerticalGroup(
            daftarPerawatanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daftarPerawatanPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(daftarPerawatanLabel)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pemilikPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anabulPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daftarPerawatanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pemilikPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anabulPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(daftarPerawatanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(403, Short.MAX_VALUE))
        );

        contentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        contentPanel.setOpaque(false);
        contentPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pemilikPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pemilikPanelMouseClicked
        if(selectedIndex == 1)
            return;
        
        recolorDefaultSwitchPanel();
        pemilikPanel.setBackground(new Color(241, 53, 21, 200));
        setForm(new PemilikMainPanel());
        selectedIndex = 1;
    }//GEN-LAST:event_pemilikPanelMouseClicked

    private void anabulPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anabulPanelMouseClicked
        if(selectedIndex == 2)
            return;
        
        recolorDefaultSwitchPanel();
        anabulPanel.setBackground(new Color(241, 53, 21, 200));
        setForm(new AnabulMainPanel());
        selectedIndex = 2;
    }//GEN-LAST:event_anabulPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainViewForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anabulLabel;
    private javax.swing.JPanel anabulPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel daftarPerawatanLabel;
    private javax.swing.JPanel daftarPerawatanPanel;
    private javax.swing.JLabel logoIcon;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel pemilikLabel;
    private javax.swing.JPanel pemilikPanel;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
